let FRACBITS = 16
let FRACUNIT = (1 << FRACBITS)
let MAXRADIUS = 32 * FRACUNIT
let MAPBLOCKSHIFT = FRACBITS + 7

// Call P_SpecialThing when touched.
let MF_SPECIAL = 1
// Blocks.
let MF_SOLID = 2
// Can be hit.
let MF_SHOOTABLE = 4
// Don't use the sector links (invisible but touchable).
let MF_NOSECTOR = 8
// Don't use the blocklinks (inert but displayable)
let MF_NOBLOCKMAP = 16
// Not to be activated by sound, deaf monster.
let MF_AMBUSH = 32
// Will try to attack right back.
let MF_JUSTHIT = 64
// Will take at least one step before attacking.
let MF_JUSTATTACKED = 128
// On level spawning (initial position),
//  hang from ceiling instead of stand on floor.
let MF_SPAWNCEILING = 256
// Don't apply gravity (every tic),
//  that is, object will float, keeping current height
//  or changing it actively.
let MF_NOGRAVITY = 512

// Movement flags.
// This allows jumps from high places.
let MF_DROPOFF = 0x400
// For players, will pick up items.
let MF_PICKUP = 0x800
// Player cheat. ???
let MF_NOCLIP = 0x1000
// Player: keep info about sliding along walls.
let MF_SLIDE = 0x2000
// Allow moves to any height, no gravity.
// For active floaters, e.g. cacodemons, pain elementals.
let MF_FLOAT = 0x4000
// Don't cross lines
//   ??? or look at heights on teleport.
let MF_TELEPORT = 0x8000
// Don't hit same species, explode on block.
// Player missiles as well as fireballs of various kinds.
let MF_MISSILE = 0x10000
// Dropped by a demon, not level spawned.
// E.g. ammo clips dropped by dying former humans.
let MF_DROPPED = 0x20000
// Use fuzzy draw (shadow demons or spectres),
//  temporary player invisibility powerup.
let MF_SHADOW = 0x40000
// Flag: don't bleed when shot (use puff),
//  barrels and shootable furniture shall not bleed.
let MF_NOBLOOD = 0x80000
// Don't stop moving halfway off a step,
//  that is, have dead bodies slide down all the way.
let MF_CORPSE = 0x100000
// Floating to a height for a move, ???
//  don't auto float to target's height.
let MF_INFLOAT = 0x200000

// On kill, count this enemy object
//  towards intermission kill total.
// Happy gathering.
let MF_COUNTKILL = 0x400000

// On picking up, count this item object
//  towards intermission item total.
let MF_COUNTITEM = 0x800000

// Special handling: skull in flight.
// Neither a cacodemon nor a missile.
let MF_SKULLFLY = 0x1000000

// Don't spawn this object
//  in death match mode (e.g. key cards).
let MF_NOTDMATCH = 0x2000000

// Player sprites in multiplayer modes are modified
//  using an internal color lookup table for re-indexing.
// If 0x4 0x8 or 0xc,
//  use a translation table for player colormaps
let MF_TRANSLATION = 0xc000000
// Hmm ???.
let MF_TRANSSHIFT = 26

// Replace with
// / +([0-9A-Za-z_|\*\-]+),?.+\/\/ (.+)/g
// $2: "$1",

// radius: "([0-9]+)\*([A-Z]+)"
// radius: $1*$2
// height: "([0-9]+)\*([A-Z]+)"
// height: $1*$2
// doomednum: "(-?[0-9]+)"
// doomednum: $1
function mobjobinfos() {
    let map = {}
    for (const mobjinfo of mobjinfos) {
        map[mobjinfo.doomednum] = mobjinfo
    }
    return map
}
let mobjinfos = [
    {		// MT_PLAYER
        doomednum: 1,
        spawnstate: "S_PLAY",
        spawnhealth: "100",
        seestate: "S_PLAY_RUN1",
        seesound: "sfx_None",
        reactiontime: "0",
        attacksound: "sfx_None",
        painstate: "S_PLAY_PAIN",
        painchance: "255",
        painsound: "sfx_plpain",
        meleestate: "S_NULL",
        missilestate: "S_PLAY_ATK1",
        deathstate: "S_PLAY_DIE1",
        xdeathstate: "S_PLAY_XDIE1",
        deathsound: "sfx_pldeth",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 56 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID | MF_SHOOTABLE | MF_DROPOFF | MF_PICKUP | MF_NOTDMATCH,
        raisestate: "S_NULL",
    },

    {		// MT_POSSESSED
        doomednum: 3004,
        spawnstate: "S_POSS_STND",
        spawnhealth: "20",
        seestate: "S_POSS_RUN1",
        seesound: "sfx_posit1",
        reactiontime: "8",
        attacksound: "sfx_pistol",
        painstate: "S_POSS_PAIN",
        painchance: "200",
        painsound: "sfx_popain",
        meleestate: "0",
        missilestate: "S_POSS_ATK1",
        deathstate: "S_POSS_DIE1",
        xdeathstate: "S_POSS_XDIE1",
        deathsound: "sfx_podth1",
        speed: "8",
        radius: 20 * FRACUNIT,
        height: 56 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_posact",
        flags: MF_SOLID | MF_SHOOTABLE | MF_COUNTKILL,
        raisestate: "S_POSS_RAISE1",
    },

    {		// MT_SHOTGUY
        doomednum: 9,
        spawnstate: "S_SPOS_STND",
        spawnhealth: "30",
        seestate: "S_SPOS_RUN1",
        seesound: "sfx_posit2",
        reactiontime: "8",
        attacksound: "0",
        painstate: "S_SPOS_PAIN",
        painchance: "170",
        painsound: "sfx_popain",
        meleestate: "0",
        missilestate: "S_SPOS_ATK1",
        deathstate: "S_SPOS_DIE1",
        xdeathstate: "S_SPOS_XDIE1",
        deathsound: "sfx_podth2",
        speed: "8",
        radius: 20 * FRACUNIT,
        height: 56 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_posact",
        flags: MF_SOLID | MF_SHOOTABLE | MF_COUNTKILL,
        raisestate: "S_SPOS_RAISE1",
    },

    {		// MT_VILE
        doomednum: 64,
        spawnstate: "S_VILE_STND",
        spawnhealth: "700",
        seestate: "S_VILE_RUN1",
        seesound: "sfx_vilsit",
        reactiontime: "8",
        attacksound: "0",
        painstate: "S_VILE_PAIN",
        painchance: "10",
        painsound: "sfx_vipain",
        meleestate: "0",
        missilestate: "S_VILE_ATK1",
        deathstate: "S_VILE_DIE1",
        xdeathstate: "S_NULL",
        deathsound: "sfx_vildth",
        speed: "15",
        radius: 20 * FRACUNIT,
        height: 56 * FRACUNIT,
        mass: "500",
        damage: "0",
        activesound: "sfx_vilact",
        flags: MF_SOLID | MF_SHOOTABLE | MF_COUNTKILL,
        raisestate: "S_NULL",
    },

    {		// MT_FIRE
        doomednum: -1,
        spawnstate: "S_FIRE1",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_UNDEAD
        doomednum: 66,
        spawnstate: "S_SKEL_STND",
        spawnhealth: "300",
        seestate: "S_SKEL_RUN1",
        seesound: "sfx_skesit",
        reactiontime: "8",
        attacksound: "0",
        painstate: "S_SKEL_PAIN",
        painchance: "100",
        painsound: "sfx_popain",
        meleestate: "S_SKEL_FIST1",
        missilestate: "S_SKEL_MISS1",
        deathstate: "S_SKEL_DIE1",
        xdeathstate: "S_NULL",
        deathsound: "sfx_skedth",
        speed: "10",
        radius: 20 * FRACUNIT,
        height: 56 * FRACUNIT,
        mass: "500",
        damage: "0",
        activesound: "sfx_skeact",
        flags: MF_SOLID | MF_SHOOTABLE | MF_COUNTKILL,
        raisestate: "S_SKEL_RAISE1",
    },

    {		// MT_TRACER
        doomednum: -1,
        spawnstate: "S_TRACER",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_skeatk",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_TRACEEXP1",
        xdeathstate: "S_NULL",
        deathsound: "sfx_barexp",
        speed: "10*FRACUNIT",
        radius: 11 * FRACUNIT,
        height: 8 * FRACUNIT,
        mass: "100",
        damage: "10",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP | MF_MISSILE | MF_DROPOFF | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_SMOKE
        doomednum: -1,
        spawnstate: "S_SMOKE1",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_FATSO
        doomednum: 67,
        spawnstate: "S_FATT_STND",
        spawnhealth: "600",
        seestate: "S_FATT_RUN1",
        seesound: "sfx_mansit",
        reactiontime: "8",
        attacksound: "0",
        painstate: "S_FATT_PAIN",
        painchance: "80",
        painsound: "sfx_mnpain",
        meleestate: "0",
        missilestate: "S_FATT_ATK1",
        deathstate: "S_FATT_DIE1",
        xdeathstate: "S_NULL",
        deathsound: "sfx_mandth",
        speed: "8",
        radius: 48 * FRACUNIT,
        height: 64 * FRACUNIT,
        mass: "1000",
        damage: "0",
        activesound: "sfx_posact",
        flags: MF_SOLID | MF_SHOOTABLE | MF_COUNTKILL,
        raisestate: "S_FATT_RAISE1",
    },

    {		// MT_FATSHOT
        doomednum: -1,
        spawnstate: "S_FATSHOT1",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_firsht",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_FATSHOTX1",
        xdeathstate: "S_NULL",
        deathsound: "sfx_firxpl",
        speed: "20*FRACUNIT",
        radius: 6 * FRACUNIT,
        height: 8 * FRACUNIT,
        mass: "100",
        damage: "8",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP | MF_MISSILE | MF_DROPOFF | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_CHAINGUY
        doomednum: 65,
        spawnstate: "S_CPOS_STND",
        spawnhealth: "70",
        seestate: "S_CPOS_RUN1",
        seesound: "sfx_posit2",
        reactiontime: "8",
        attacksound: "0",
        painstate: "S_CPOS_PAIN",
        painchance: "170",
        painsound: "sfx_popain",
        meleestate: "0",
        missilestate: "S_CPOS_ATK1",
        deathstate: "S_CPOS_DIE1",
        xdeathstate: "S_CPOS_XDIE1",
        deathsound: "sfx_podth2",
        speed: "8",
        radius: 20 * FRACUNIT,
        height: 56 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_posact",
        flags: MF_SOLID | MF_SHOOTABLE | MF_COUNTKILL,
        raisestate: "S_CPOS_RAISE1",
    },

    {		// MT_TROOP
        doomednum: 3001,
        spawnstate: "S_TROO_STND",
        spawnhealth: "60",
        seestate: "S_TROO_RUN1",
        seesound: "sfx_bgsit1",
        reactiontime: "8",
        attacksound: "0",
        painstate: "S_TROO_PAIN",
        painchance: "200",
        painsound: "sfx_popain",
        meleestate: "S_TROO_ATK1",
        missilestate: "S_TROO_ATK1",
        deathstate: "S_TROO_DIE1",
        xdeathstate: "S_TROO_XDIE1",
        deathsound: "sfx_bgdth1",
        speed: "8",
        radius: 20 * FRACUNIT,
        height: 56 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_bgact",
        flags: MF_SOLID | MF_SHOOTABLE | MF_COUNTKILL,
        raisestate: "S_TROO_RAISE1",
    },

    {		// MT_SERGEANT
        doomednum: 3002,
        spawnstate: "S_SARG_STND",
        spawnhealth: "150",
        seestate: "S_SARG_RUN1",
        seesound: "sfx_sgtsit",
        reactiontime: "8",
        attacksound: "sfx_sgtatk",
        painstate: "S_SARG_PAIN",
        painchance: "180",
        painsound: "sfx_dmpain",
        meleestate: "S_SARG_ATK1",
        missilestate: "0",
        deathstate: "S_SARG_DIE1",
        xdeathstate: "S_NULL",
        deathsound: "sfx_sgtdth",
        speed: "10",
        radius: 30 * FRACUNIT,
        height: 56 * FRACUNIT,
        mass: "400",
        damage: "0",
        activesound: "sfx_dmact",
        flags: MF_SOLID | MF_SHOOTABLE | MF_COUNTKILL,
        raisestate: "S_SARG_RAISE1",
    },

    {		// MT_SHADOWS
        doomednum: 58,
        spawnstate: "S_SARG_STND",
        spawnhealth: "150",
        seestate: "S_SARG_RUN1",
        seesound: "sfx_sgtsit",
        reactiontime: "8",
        attacksound: "sfx_sgtatk",
        painstate: "S_SARG_PAIN",
        painchance: "180",
        painsound: "sfx_dmpain",
        meleestate: "S_SARG_ATK1",
        missilestate: "0",
        deathstate: "S_SARG_DIE1",
        xdeathstate: "S_NULL",
        deathsound: "sfx_sgtdth",
        speed: "10",
        radius: 30 * FRACUNIT,
        height: 56 * FRACUNIT,
        mass: "400",
        damage: "0",
        activesound: "sfx_dmact",
        flags: MF_SOLID | MF_SHOOTABLE | MF_SHADOW | MF_COUNTKILL,
        raisestate: "S_SARG_RAISE1",
    },

    {		// MT_HEAD
        doomednum: 3005,
        spawnstate: "S_HEAD_STND",
        spawnhealth: "400",
        seestate: "S_HEAD_RUN1",
        seesound: "sfx_cacsit",
        reactiontime: "8",
        attacksound: "0",
        painstate: "S_HEAD_PAIN",
        painchance: "128",
        painsound: "sfx_dmpain",
        meleestate: "0",
        missilestate: "S_HEAD_ATK1",
        deathstate: "S_HEAD_DIE1",
        xdeathstate: "S_NULL",
        deathsound: "sfx_cacdth",
        speed: "8",
        radius: 31 * FRACUNIT,
        height: 56 * FRACUNIT,
        mass: "400",
        damage: "0",
        activesound: "sfx_dmact",
        flags: MF_SOLID | MF_SHOOTABLE | MF_FLOAT | MF_NOGRAVITY | MF_COUNTKILL,
        raisestate: "S_HEAD_RAISE1",
    },

    {		// MT_BRUISER
        doomednum: 3003,
        spawnstate: "S_BOSS_STND",
        spawnhealth: "1000",
        seestate: "S_BOSS_RUN1",
        seesound: "sfx_brssit",
        reactiontime: "8",
        attacksound: "0",
        painstate: "S_BOSS_PAIN",
        painchance: "50",
        painsound: "sfx_dmpain",
        meleestate: "S_BOSS_ATK1",
        missilestate: "S_BOSS_ATK1",
        deathstate: "S_BOSS_DIE1",
        xdeathstate: "S_NULL",
        deathsound: "sfx_brsdth",
        speed: "8",
        radius: 24 * FRACUNIT,
        height: 64 * FRACUNIT,
        mass: "1000",
        damage: "0",
        activesound: "sfx_dmact",
        flags: MF_SOLID | MF_SHOOTABLE | MF_COUNTKILL,
        raisestate: "S_BOSS_RAISE1",
    },

    {		// MT_BRUISERSHOT
        doomednum: -1,
        spawnstate: "S_BRBALL1",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_firsht",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_BRBALLX1",
        xdeathstate: "S_NULL",
        deathsound: "sfx_firxpl",
        speed: "15*FRACUNIT",
        radius: 6 * FRACUNIT,
        height: 8 * FRACUNIT,
        mass: "100",
        damage: "8",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP | MF_MISSILE | MF_DROPOFF | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_KNIGHT
        doomednum: 69,
        spawnstate: "S_BOS2_STND",
        spawnhealth: "500",
        seestate: "S_BOS2_RUN1",
        seesound: "sfx_kntsit",
        reactiontime: "8",
        attacksound: "0",
        painstate: "S_BOS2_PAIN",
        painchance: "50",
        painsound: "sfx_dmpain",
        meleestate: "S_BOS2_ATK1",
        missilestate: "S_BOS2_ATK1",
        deathstate: "S_BOS2_DIE1",
        xdeathstate: "S_NULL",
        deathsound: "sfx_kntdth",
        speed: "8",
        radius: 24 * FRACUNIT,
        height: 64 * FRACUNIT,
        mass: "1000",
        damage: "0",
        activesound: "sfx_dmact",
        flags: MF_SOLID | MF_SHOOTABLE | MF_COUNTKILL,
        raisestate: "S_BOS2_RAISE1",
    },

    {		// MT_SKULL
        doomednum: 3006,
        spawnstate: "S_SKULL_STND",
        spawnhealth: "100",
        seestate: "S_SKULL_RUN1",
        seesound: "0",
        reactiontime: "8",
        attacksound: "sfx_sklatk",
        painstate: "S_SKULL_PAIN",
        painchance: "256",
        painsound: "sfx_dmpain",
        meleestate: "0",
        missilestate: "S_SKULL_ATK1",
        deathstate: "S_SKULL_DIE1",
        xdeathstate: "S_NULL",
        deathsound: "sfx_firxpl",
        speed: "8",
        radius: 16 * FRACUNIT,
        height: 56 * FRACUNIT,
        mass: "50",
        damage: "3",
        activesound: "sfx_dmact",
        flags: MF_SOLID | MF_SHOOTABLE | MF_FLOAT | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_SPIDER
        doomednum: 7,
        spawnstate: "S_SPID_STND",
        spawnhealth: "3000",
        seestate: "S_SPID_RUN1",
        seesound: "sfx_spisit",
        reactiontime: "8",
        attacksound: "sfx_shotgn",
        painstate: "S_SPID_PAIN",
        painchance: "40",
        painsound: "sfx_dmpain",
        meleestate: "0",
        missilestate: "S_SPID_ATK1",
        deathstate: "S_SPID_DIE1",
        xdeathstate: "S_NULL",
        deathsound: "sfx_spidth",
        speed: "12",
        radius: 128 * FRACUNIT,
        height: 100 * FRACUNIT,
        mass: "1000",
        damage: "0",
        activesound: "sfx_dmact",
        flags: MF_SOLID | MF_SHOOTABLE | MF_COUNTKILL,
        raisestate: "S_NULL",
    },

    {		// MT_BABY
        doomednum: 68,
        spawnstate: "S_BSPI_STND",
        spawnhealth: "500",
        seestate: "S_BSPI_SIGHT",
        seesound: "sfx_bspsit",
        reactiontime: "8",
        attacksound: "0",
        painstate: "S_BSPI_PAIN",
        painchance: "128",
        painsound: "sfx_dmpain",
        meleestate: "0",
        missilestate: "S_BSPI_ATK1",
        deathstate: "S_BSPI_DIE1",
        xdeathstate: "S_NULL",
        deathsound: "sfx_bspdth",
        speed: "12",
        radius: 64 * FRACUNIT,
        height: 64 * FRACUNIT,
        mass: "600",
        damage: "0",
        activesound: "sfx_bspact",
        flags: MF_SOLID | MF_SHOOTABLE | MF_COUNTKILL,
        raisestate: "S_BSPI_RAISE1",
    },

    {		// MT_CYBORG
        doomednum: 16,
        spawnstate: "S_CYBER_STND",
        spawnhealth: "4000",
        seestate: "S_CYBER_RUN1",
        seesound: "sfx_cybsit",
        reactiontime: "8",
        attacksound: "0",
        painstate: "S_CYBER_PAIN",
        painchance: "20",
        painsound: "sfx_dmpain",
        meleestate: "0",
        missilestate: "S_CYBER_ATK1",
        deathstate: "S_CYBER_DIE1",
        xdeathstate: "S_NULL",
        deathsound: "sfx_cybdth",
        speed: "16",
        radius: 40 * FRACUNIT,
        height: 110 * FRACUNIT,
        mass: "1000",
        damage: "0",
        activesound: "sfx_dmact",
        flags: MF_SOLID | MF_SHOOTABLE | MF_COUNTKILL,
        raisestate: "S_NULL",
    },

    {		// MT_PAIN
        doomednum: 71,
        spawnstate: "S_PAIN_STND",
        spawnhealth: "400",
        seestate: "S_PAIN_RUN1",
        seesound: "sfx_pesit",
        reactiontime: "8",
        attacksound: "0",
        painstate: "S_PAIN_PAIN",
        painchance: "128",
        painsound: "sfx_pepain",
        meleestate: "0",
        missilestate: "S_PAIN_ATK1",
        deathstate: "S_PAIN_DIE1",
        xdeathstate: "S_NULL",
        deathsound: "sfx_pedth",
        speed: "8",
        radius: 31 * FRACUNIT,
        height: 56 * FRACUNIT,
        mass: "400",
        damage: "0",
        activesound: "sfx_dmact",
        flags: MF_SOLID | MF_SHOOTABLE | MF_FLOAT | MF_NOGRAVITY | MF_COUNTKILL,
        raisestate: "S_PAIN_RAISE1",
    },

    {		// MT_WOLFSS
        doomednum: 84,
        spawnstate: "S_SSWV_STND",
        spawnhealth: "50",
        seestate: "S_SSWV_RUN1",
        seesound: "sfx_sssit",
        reactiontime: "8",
        attacksound: "0",
        painstate: "S_SSWV_PAIN",
        painchance: "170",
        painsound: "sfx_popain",
        meleestate: "0",
        missilestate: "S_SSWV_ATK1",
        deathstate: "S_SSWV_DIE1",
        xdeathstate: "S_SSWV_XDIE1",
        deathsound: "sfx_ssdth",
        speed: "8",
        radius: 20 * FRACUNIT,
        height: 56 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_posact",
        flags: MF_SOLID | MF_SHOOTABLE | MF_COUNTKILL,
        raisestate: "S_SSWV_RAISE1",
    },

    {		// MT_KEEN
        doomednum: 72,
        spawnstate: "S_KEENSTND",
        spawnhealth: "100",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_KEENPAIN",
        painchance: "256",
        painsound: "sfx_keenpn",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_COMMKEEN",
        xdeathstate: "S_NULL",
        deathsound: "sfx_keendt",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 72 * FRACUNIT,
        mass: "10000000",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID | MF_SPAWNCEILING | MF_NOGRAVITY | MF_SHOOTABLE | MF_COUNTKILL,
        raisestate: "S_NULL",
    },

    {		// MT_BOSSBRAIN
        doomednum: 88,
        spawnstate: "S_BRAIN",
        spawnhealth: "250",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_BRAIN_PAIN",
        painchance: "255",
        painsound: "sfx_bospn",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_BRAIN_DIE1",
        xdeathstate: "S_NULL",
        deathsound: "sfx_bosdth",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "10000000",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID | MF_SHOOTABLE,
        raisestate: "S_NULL",
    },

    {		// MT_BOSSSPIT
        doomednum: 89,
        spawnstate: "S_BRAINEYE",
        spawnhealth: "1000",
        seestate: "S_BRAINEYESEE",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 32 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP | MF_NOSECTOR,
        raisestate: "S_NULL",
    },

    {		// MT_BOSSTARGET
        doomednum: 87,
        spawnstate: "S_NULL",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 32 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP | MF_NOSECTOR,
        raisestate: "S_NULL",
    },

    {		// MT_SPAWNSHOT
        doomednum: -1,
        spawnstate: "S_SPAWN1",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_bospit",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_firxpl",
        speed: "10*FRACUNIT",
        radius: 6 * FRACUNIT,
        height: 32 * FRACUNIT,
        mass: "100",
        damage: "3",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP | MF_MISSILE | MF_DROPOFF | MF_NOGRAVITY | MF_NOCLIP,
        raisestate: "S_NULL",
    },

    {		// MT_SPAWNFIRE
        doomednum: -1,
        spawnstate: "S_SPAWNFIRE1",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_BARREL
        doomednum: 2035,
        spawnstate: "S_BAR1",
        spawnhealth: "20",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_BEXP",
        xdeathstate: "S_NULL",
        deathsound: "sfx_barexp",
        speed: "0",
        radius: 10 * FRACUNIT,
        height: 42 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID | MF_SHOOTABLE | MF_NOBLOOD,
        raisestate: "S_NULL",
    },

    {		// MT_TROOPSHOT
        doomednum: -1,
        spawnstate: "S_TBALL1",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_firsht",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_TBALLX1",
        xdeathstate: "S_NULL",
        deathsound: "sfx_firxpl",
        speed: "10*FRACUNIT",
        radius: 6 * FRACUNIT,
        height: 8 * FRACUNIT,
        mass: "100",
        damage: "3",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP | MF_MISSILE | MF_DROPOFF | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_HEADSHOT
        doomednum: -1,
        spawnstate: "S_RBALL1",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_firsht",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_RBALLX1",
        xdeathstate: "S_NULL",
        deathsound: "sfx_firxpl",
        speed: "10*FRACUNIT",
        radius: 6 * FRACUNIT,
        height: 8 * FRACUNIT,
        mass: "100",
        damage: "5",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP | MF_MISSILE | MF_DROPOFF | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_ROCKET
        doomednum: -1,
        spawnstate: "S_ROCKET",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_rlaunc",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_EXPLODE1",
        xdeathstate: "S_NULL",
        deathsound: "sfx_barexp",
        speed: "20*FRACUNIT",
        radius: 11 * FRACUNIT,
        height: 8 * FRACUNIT,
        mass: "100",
        damage: "20",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP | MF_MISSILE | MF_DROPOFF | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_PLASMA
        doomednum: -1,
        spawnstate: "S_PLASBALL",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_plasma",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_PLASEXP",
        xdeathstate: "S_NULL",
        deathsound: "sfx_firxpl",
        speed: "25*FRACUNIT",
        radius: 13 * FRACUNIT,
        height: 8 * FRACUNIT,
        mass: "100",
        damage: "5",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP | MF_MISSILE | MF_DROPOFF | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_BFG
        doomednum: -1,
        spawnstate: "S_BFGSHOT",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "0",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_BFGLAND",
        xdeathstate: "S_NULL",
        deathsound: "sfx_rxplod",
        speed: "25*FRACUNIT",
        radius: 13 * FRACUNIT,
        height: 8 * FRACUNIT,
        mass: "100",
        damage: "100",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP | MF_MISSILE | MF_DROPOFF | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_ARACHPLAZ
        doomednum: -1,
        spawnstate: "S_ARACH_PLAZ",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_plasma",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_ARACH_PLEX",
        xdeathstate: "S_NULL",
        deathsound: "sfx_firxpl",
        speed: "25*FRACUNIT",
        radius: 13 * FRACUNIT,
        height: 8 * FRACUNIT,
        mass: "100",
        damage: "5",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP | MF_MISSILE | MF_DROPOFF | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_PUFF
        doomednum: -1,
        spawnstate: "S_PUFF1",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_BLOOD
        doomednum: -1,
        spawnstate: "S_BLOOD1",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP,
        raisestate: "S_NULL",
    },

    {		// MT_TFOG
        doomednum: -1,
        spawnstate: "S_TFOG",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_IFOG
        doomednum: -1,
        spawnstate: "S_IFOG",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_TELEPORTMAN
        doomednum: 14,
        spawnstate: "S_NULL",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP | MF_NOSECTOR,
        raisestate: "S_NULL",
    },

    {		// MT_EXTRABFG
        doomednum: -1,
        spawnstate: "S_BFGEXP",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_MISC0
        doomednum: 2018,
        spawnstate: "S_ARM1",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL,
        raisestate: "S_NULL",
    },

    {		// MT_MISC1
        doomednum: 2019,
        spawnstate: "S_ARM2",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL,
        raisestate: "S_NULL",
    },

    {		// MT_MISC2
        doomednum: 2014,
        spawnstate: "S_BON1",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL | MF_COUNTITEM,
        raisestate: "S_NULL",
    },

    {		// MT_MISC3
        doomednum: 2015,
        spawnstate: "S_BON2",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL | MF_COUNTITEM,
        raisestate: "S_NULL",
    },

    {		// MT_MISC4
        doomednum: 5,
        spawnstate: "S_BKEY",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL | MF_NOTDMATCH,
        raisestate: "S_NULL",
    },

    {		// MT_MISC5
        doomednum: 13,
        spawnstate: "S_RKEY",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL | MF_NOTDMATCH,
        raisestate: "S_NULL",
    },

    {		// MT_MISC6
        doomednum: 6,
        spawnstate: "S_YKEY",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL | MF_NOTDMATCH,
        raisestate: "S_NULL",
    },

    {		// MT_MISC7
        doomednum: 39,
        spawnstate: "S_YSKULL",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL | MF_NOTDMATCH,
        raisestate: "S_NULL",
    },

    {		// MT_MISC8
        doomednum: 38,
        spawnstate: "S_RSKULL",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL | MF_NOTDMATCH,
        raisestate: "S_NULL",
    },

    {		// MT_MISC9
        doomednum: 40,
        spawnstate: "S_BSKULL",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL | MF_NOTDMATCH,
        raisestate: "S_NULL",
    },

    {		// MT_MISC10
        doomednum: 2011,
        spawnstate: "S_STIM",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL,
        raisestate: "S_NULL",
    },

    {		// MT_MISC11
        doomednum: 2012,
        spawnstate: "S_MEDI",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL,
        raisestate: "S_NULL",
    },

    {		// MT_MISC12
        doomednum: 2013,
        spawnstate: "S_SOUL",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL | MF_COUNTITEM,
        raisestate: "S_NULL",
    },

    {		// MT_INV
        doomednum: 2022,
        spawnstate: "S_PINV",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL | MF_COUNTITEM,
        raisestate: "S_NULL",
    },

    {		// MT_MISC13
        doomednum: 2023,
        spawnstate: "S_PSTR",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL | MF_COUNTITEM,
        raisestate: "S_NULL",
    },

    {		// MT_INS
        doomednum: 2024,
        spawnstate: "S_PINS",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL | MF_COUNTITEM,
        raisestate: "S_NULL",
    },

    {		// MT_MISC14
        doomednum: 2025,
        spawnstate: "S_SUIT",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL,
        raisestate: "S_NULL",
    },

    {		// MT_MISC15
        doomednum: 2026,
        spawnstate: "S_PMAP",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL | MF_COUNTITEM,
        raisestate: "S_NULL",
    },

    {		// MT_MISC16
        doomednum: 2045,
        spawnstate: "S_PVIS",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL | MF_COUNTITEM,
        raisestate: "S_NULL",
    },

    {		// MT_MEGA
        doomednum: 83,
        spawnstate: "S_MEGA",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL | MF_COUNTITEM,
        raisestate: "S_NULL",
    },

    {		// MT_CLIP
        doomednum: 2007,
        spawnstate: "S_CLIP",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL,
        raisestate: "S_NULL",
    },

    {		// MT_MISC17
        doomednum: 2048,
        spawnstate: "S_AMMO",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL,
        raisestate: "S_NULL",
    },

    {		// MT_MISC18
        doomednum: 2010,
        spawnstate: "S_ROCK",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL,
        raisestate: "S_NULL",
    },

    {		// MT_MISC19
        doomednum: 2046,
        spawnstate: "S_BROK",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL,
        raisestate: "S_NULL",
    },

    {		// MT_MISC20
        doomednum: 2047,
        spawnstate: "S_CELL",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL,
        raisestate: "S_NULL",
    },

    {		// MT_MISC21
        doomednum: 17,
        spawnstate: "S_CELP",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL,
        raisestate: "S_NULL",
    },

    {		// MT_MISC22
        doomednum: 2008,
        spawnstate: "S_SHEL",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL,
        raisestate: "S_NULL",
    },

    {		// MT_MISC23
        doomednum: 2049,
        spawnstate: "S_SBOX",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL,
        raisestate: "S_NULL",
    },

    {		// MT_MISC24
        doomednum: 8,
        spawnstate: "S_BPAK",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL,
        raisestate: "S_NULL",
    },

    {		// MT_MISC25
        doomednum: 2006,
        spawnstate: "S_BFUG",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL,
        raisestate: "S_NULL",
    },

    {		// MT_CHAINGUN
        doomednum: 2002,
        spawnstate: "S_MGUN",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL,
        raisestate: "S_NULL",
    },

    {		// MT_MISC26
        doomednum: 2005,
        spawnstate: "S_CSAW",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL,
        raisestate: "S_NULL",
    },

    {		// MT_MISC27
        doomednum: 2003,
        spawnstate: "S_LAUN",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL,
        raisestate: "S_NULL",
    },

    {		// MT_MISC28
        doomednum: 2004,
        spawnstate: "S_PLAS",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL,
        raisestate: "S_NULL",
    },

    {		// MT_SHOTGUN
        doomednum: 2001,
        spawnstate: "S_SHOT",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL,
        raisestate: "S_NULL",
    },

    {		// MT_SUPERSHOTGUN
        doomednum: 82,
        spawnstate: "S_SHOT2",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPECIAL,
        raisestate: "S_NULL",
    },

    {		// MT_MISC29
        doomednum: 85,
        spawnstate: "S_TECHLAMP",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC30
        doomednum: 86,
        spawnstate: "S_TECH2LAMP",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC31
        doomednum: 2028,
        spawnstate: "S_COLU",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC32
        doomednum: 30,
        spawnstate: "S_TALLGRNCOL",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC33
        doomednum: 31,
        spawnstate: "S_SHRTGRNCOL",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC34
        doomednum: 32,
        spawnstate: "S_TALLREDCOL",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC35
        doomednum: 33,
        spawnstate: "S_SHRTREDCOL",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC36
        doomednum: 37,
        spawnstate: "S_SKULLCOL",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC37
        doomednum: 36,
        spawnstate: "S_HEARTCOL",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC38
        doomednum: 41,
        spawnstate: "S_EVILEYE",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC39
        doomednum: 42,
        spawnstate: "S_FLOATSKULL",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC40
        doomednum: 43,
        spawnstate: "S_TORCHTREE",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC41
        doomednum: 44,
        spawnstate: "S_BLUETORCH",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC42
        doomednum: 45,
        spawnstate: "S_GREENTORCH",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC43
        doomednum: 46,
        spawnstate: "S_REDTORCH",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC44
        doomednum: 55,
        spawnstate: "S_BTORCHSHRT",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC45
        doomednum: 56,
        spawnstate: "S_GTORCHSHRT",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC46
        doomednum: 57,
        spawnstate: "S_RTORCHSHRT",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC47
        doomednum: 47,
        spawnstate: "S_STALAGTITE",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC48
        doomednum: 48,
        spawnstate: "S_TECHPILLAR",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC49
        doomednum: 34,
        spawnstate: "S_CANDLESTIK",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: 0,
        raisestate: "S_NULL",
    },

    {		// MT_MISC50
        doomednum: 35,
        spawnstate: "S_CANDELABRA",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC51
        doomednum: 49,
        spawnstate: "S_BLOODYTWITCH",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 68 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID | MF_SPAWNCEILING | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_MISC52
        doomednum: 50,
        spawnstate: "S_MEAT2",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 84 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID | MF_SPAWNCEILING | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_MISC53
        doomednum: 51,
        spawnstate: "S_MEAT3",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 84 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID | MF_SPAWNCEILING | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_MISC54
        doomednum: 52,
        spawnstate: "S_MEAT4",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 68 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID | MF_SPAWNCEILING | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_MISC55
        doomednum: 53,
        spawnstate: "S_MEAT5",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 52 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID | MF_SPAWNCEILING | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_MISC56
        doomednum: 59,
        spawnstate: "S_MEAT2",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 84 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPAWNCEILING | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_MISC57
        doomednum: 60,
        spawnstate: "S_MEAT4",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 68 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPAWNCEILING | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_MISC58
        doomednum: 61,
        spawnstate: "S_MEAT3",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 52 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPAWNCEILING | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_MISC59
        doomednum: 62,
        spawnstate: "S_MEAT5",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 52 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPAWNCEILING | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_MISC60
        doomednum: 63,
        spawnstate: "S_BLOODYTWITCH",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 68 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SPAWNCEILING | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_MISC61
        doomednum: 22,
        spawnstate: "S_HEAD_DIE6",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: 0,
        raisestate: "S_NULL",
    },

    {		// MT_MISC62
        doomednum: 15,
        spawnstate: "S_PLAY_DIE7",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: 0,
        raisestate: "S_NULL",
    },

    {		// MT_MISC63
        doomednum: 18,
        spawnstate: "S_POSS_DIE5",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: 0,
        raisestate: "S_NULL",
    },

    {		// MT_MISC64
        doomednum: 21,
        spawnstate: "S_SARG_DIE6",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: 0,
        raisestate: "S_NULL",
    },

    {		// MT_MISC65
        doomednum: 23,
        spawnstate: "S_SKULL_DIE6",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: 0,
        raisestate: "S_NULL",
    },

    {		// MT_MISC66
        doomednum: 20,
        spawnstate: "S_TROO_DIE5",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: 0,
        raisestate: "S_NULL",
    },

    {		// MT_MISC67
        doomednum: 19,
        spawnstate: "S_SPOS_DIE5",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: 0,
        raisestate: "S_NULL",
    },

    {		// MT_MISC68
        doomednum: 10,
        spawnstate: "S_PLAY_XDIE9",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: 0,
        raisestate: "S_NULL",
    },

    {		// MT_MISC69
        doomednum: 12,
        spawnstate: "S_PLAY_XDIE9",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: 0,
        raisestate: "S_NULL",
    },

    {		// MT_MISC70
        doomednum: 28,
        spawnstate: "S_HEADSONSTICK",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC71
        doomednum: 24,
        spawnstate: "S_GIBS",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: 0,
        raisestate: "S_NULL",
    },

    {		// MT_MISC72
        doomednum: 27,
        spawnstate: "S_HEADONASTICK",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC73
        doomednum: 29,
        spawnstate: "S_HEADCANDLES",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC74
        doomednum: 25,
        spawnstate: "S_DEADSTICK",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC75
        doomednum: 26,
        spawnstate: "S_LIVESTICK",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC76
        doomednum: 54,
        spawnstate: "S_BIGTREE",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 32 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC77
        doomednum: 70,
        spawnstate: "S_BBAR1",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID,
        raisestate: "S_NULL",
    },

    {		// MT_MISC78
        doomednum: 73,
        spawnstate: "S_HANGNOGUTS",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 88 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID | MF_SPAWNCEILING | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_MISC79
        doomednum: 74,
        spawnstate: "S_HANGBNOBRAIN",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 88 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID | MF_SPAWNCEILING | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_MISC80
        doomednum: 75,
        spawnstate: "S_HANGTLOOKDN",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 64 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID | MF_SPAWNCEILING | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_MISC81
        doomednum: 76,
        spawnstate: "S_HANGTSKULL",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 64 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID | MF_SPAWNCEILING | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_MISC82
        doomednum: 77,
        spawnstate: "S_HANGTLOOKUP",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 64 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID | MF_SPAWNCEILING | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_MISC83
        doomednum: 78,
        spawnstate: "S_HANGTNOBRAIN",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 16 * FRACUNIT,
        height: 64 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_SOLID | MF_SPAWNCEILING | MF_NOGRAVITY,
        raisestate: "S_NULL",
    },

    {		// MT_MISC84
        doomednum: 79,
        spawnstate: "S_COLONGIBS",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP,
        raisestate: "S_NULL",
    },

    {		// MT_MISC85
        doomednum: 80,
        spawnstate: "S_SMALLPOOL",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP,
        raisestate: "S_NULL",
    },

    {		// MT_MISC86
        doomednum: 81,
        spawnstate: "S_BRAINSTEM",
        spawnhealth: "1000",
        seestate: "S_NULL",
        seesound: "sfx_None",
        reactiontime: "8",
        attacksound: "sfx_None",
        painstate: "S_NULL",
        painchance: "0",
        painsound: "sfx_None",
        meleestate: "S_NULL",
        missilestate: "S_NULL",
        deathstate: "S_NULL",
        xdeathstate: "S_NULL",
        deathsound: "sfx_None",
        speed: "0",
        radius: 20 * FRACUNIT,
        height: 16 * FRACUNIT,
        mass: "100",
        damage: "0",
        activesound: "sfx_None",
        flags: MF_NOBLOCKMAP,
        raisestate: "S_NULL",
    }
]